### PR TITLE
style: prefer immutable

### PR DESCRIPTION
**Pull request by nomyfan**
Code style changes.

### CODE REVIEW

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
This requires at least Rust 1.41, while the MSRV here is 1.30.

**Comment by nomyfan** [comment]
It seems that 1.3.0 doesn't have map_or, so close it.

**Comment by nomyfan** [comment]
It supports 1.30.0 now, pls take a look 👀

**Review by sdroege — APPROVED** [review]

**Comment by sdroege** [comment]
Thanks!

**Pull request merged**
