### PR TITLE
do not restrict version range when probing --modversion

### LINKED ISSUE #150: fails with pkgconf 2.0.0 breaking changes
running pkg-config crate version `0.3.27`
```
  --- stderr
  pkg_config failed: `PKG_CONFIG_ALLOW_SYSTEM_CFLAGS="1" PKG_CONFIG_ALLOW_SYSTEM_LIBS="1" "pkg-config" "--modversion" "dbus-1" "dbus-1 >= 1.6"` did not exit successfully: exit status: 1
  --- stderr
  pkgconf: --modversion requested with multiple packages, output would be ambiguous

  One possible solution is to check whether packages
  'libdbus-1-dev' and 'pkg-config' are installed:
  On Ubuntu:
  sudo apt install libdbus-1-dev pkg-config
  On Fedora:
  sudo dnf install dbus-devel pkgconf-pkg-config

  thread 'main' panicked at 'explicit panic', /home/lauren/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libdbus-sys-0.2.5/build.rs:25:9
```

the command should only mention the library once, with the version

### PR DESCRIPTION
**Pull request by selfisekai**
this should fix the crate with a pkgconf 2.0.0 breaking change (closes #150)

### CODE REVIEW

**Comment by ptrcnull** [comment]
moved my comment from the commit into here:
> wouldn't it be better to omit the first name with modversion? the main issue is that it's printing the same name twice, former without any constraint, latter with one; it would be useful to still keep the constraint, just... not put the same package name twice

**Comment by ptrcnull** [comment]
with some experimenting, i feel like this should be enough:
```diff
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -499,7 +499,9 @@ impl Config {
         if self.print_system_cflags {
             cmd.env("PKG_CONFIG_ALLOW_SYSTEM_CFLAGS", "1");
         }
-        cmd.arg(name);
+        if self.min_version == Bound::Unbounded && self.max_version == Bound::Unbounded {
+            cmd.arg(name);
+        }
         match self.min_version {
             Bound::Included(ref version) => {
                 cmd.arg(&format!("{} >= {}", name, version));
```

**Comment by selfisekai** [comment]
when running `Config::probe`, it first executes `--libs --cflags` first, where these bounds are checked by pkgconf without a problem, and only then checks `--modversion`. if they're not met, an error is already returned earlier. I think this covers the whole public API. another question is whether this can introduce some quirks with multiple library versions available? but that's an edge case I think we might not have in alpine.

**Comment by ptrcnull** [comment]
> another question is whether this can introduce some quirks with multiple library versions available?

both pkgconf and pkg-config seem to handle it by returning the first one from their search path:
```
$ rg '^Version' /usr/local/lib/pkgconfig/dbus-1.pc
18:Version: 1.15.8
$ rg '^Version' /usr/lib/pkgconfig/dbus-1.pc      
18:Version: 1.14.8
$ pkg-config --modversion dbus-1
1.15.8
$ pkg-config --modversion 'dbus-1 < 1.15'
Package dependency requirement 'dbus-1 < 1.15' could not be satisfied.
Package 'dbus-1' has version '1.15.8', required version is '< 1.15'
```

```
root@a32a659efc83:/# grep Version /usr/lib/x86_64-linux-gnu/pkgconfig/dbus-1.pc 
Version: 1.12.16
root@a32a659efc83:/# grep Version /usr/local/lib/pkgconfig/dbus-1.pc
Version: 1.13.0
root@a32a659efc83:/# pkg-config --modversion dbus-1
1.13.0
root@a32a659efc83:/# pkg-config --modversion 'dbus-1 < 1.13'
Requested 'dbus-1 < 1.13' but version of dbus is 1.13.0
```

**Comment by sdroege** [comment]
It seems like this is considered a bug in pkgconf, so maybe let's just wait until it's fixed there instead of adding a complicated workaround here.

**Comment by selfisekai** [comment]
fixed in pkgconf 2.0.1 https://github.com/pkgconf/pkgconf/releases/tag/pkgconf-2.0.1

**Pull request closed without merging**
