### PR TITLE
Remove deprecated functionalities

### LINKED ISSUE #79: Deprecated items being used
The compiler and RLS complaint about two deprecated items being used:

```
use of deprecated item 'std::ascii::AsciiExt': use inherent methods instead

note: #[warn(deprecated)] on by default
```

```
use of deprecated item 'core::str::<impl str>::trim_right': superseded by `trim_end`
```

It'll be better to removed such dependency on deprecated functionalities.

### PR DESCRIPTION
**Pull request by lwshang**
Fix #79

### CODE REVIEW

**Comment by sdroege** [comment]
The problem with this is that it requires a newer Rust version than `pkg-config` currently supports as its minimum version. 1.26 for `AsciiExt` and 1.33 for `trim_right`.

@alexcrichton what's your opinion on this?

**Comment by lwshang** [comment]
Got it.` AsciiExt` is only imported but not used actually. So this crate has already abandoned support `rustc` before 1.23.0 (char::to_ascii_uppercase since this version). Such issue should be quite common when we want to make "system" crates like `pkg-config-rs` support all versions of `rustc` in which some `std` functionalities have been deprecated. It's better to have some consistent policies on how to deal with that.

**Comment by alexcrichton** [comment]
My personal opinion has always been that the current and previous rustc versions should be required to be supported, and anything else is best effort but can change at any time.

**Comment by lwshang** [comment]
@sdroege Rust 1.34 has been published. Shall we merge this PR as you said?

**Comment by efx** [comment]
@lwshang looks like there are some merge conflicts. Would you mind rebasing against master so we can merge this? Thank you for fixing the deprecations too; cleared away the noise nicely while running `cargo test`.

**Comment by sdroege** [comment]
> @sdroege Rust 1.34 has been published. Shall we merge this PR as you said?

Sorry, completely forgot about this one! Thanks for reviving it @efx 

If you don't want to rebase your branch, I'll take a look at updating it in the next days.

**Comment by sdroege** [comment]
> and 1.33 for `trim_right`

Actually only 1.30.0

**Pull request merged**
